// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_SFYBYYN1N-4cWnNg_yMSuohhrHQs0w',
    appId: '1:1047639560548:web:5cbeaa161f5197bbe26a71',
    messagingSenderId: '1047639560548',
    projectId: 'knit-crochet-app-6488e',
    authDomain: 'knit-crochet-app-6488e.firebaseapp.com',
    storageBucket: 'knit-crochet-app-6488e.firebasestorage.app',
    measurementId: 'G-SVJ6G90KRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwGU4VuuoO1CE-cRTALSEZQxVgTfivBz8',
    appId: '1:1047639560548:android:25744fb60e8de527e26a71',
    messagingSenderId: '1047639560548',
    projectId: 'knit-crochet-app-6488e',
    storageBucket: 'knit-crochet-app-6488e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUmfOACIvFiyrehKSjRxN2XGSuBd6FJH0',
    appId: '1:1047639560548:ios:41d593e8bc998a3de26a71',
    messagingSenderId: '1047639560548',
    projectId: 'knit-crochet-app-6488e',
    storageBucket: 'knit-crochet-app-6488e.firebasestorage.app',
    iosClientId: '1047639560548-vp7sfipfuk5t0oeojthi8bdg5ea534ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.knittingCrochetRepository',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUmfOACIvFiyrehKSjRxN2XGSuBd6FJH0',
    appId: '1:1047639560548:ios:41d593e8bc998a3de26a71',
    messagingSenderId: '1047639560548',
    projectId: 'knit-crochet-app-6488e',
    storageBucket: 'knit-crochet-app-6488e.firebasestorage.app',
    iosClientId: '1047639560548-vp7sfipfuk5t0oeojthi8bdg5ea534ol.apps.googleusercontent.com',
    iosBundleId: 'com.example.knittingCrochetRepository',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN_SFYBYYN1N-4cWnNg_yMSuohhrHQs0w',
    appId: '1:1047639560548:web:1acc88e397606745e26a71',
    messagingSenderId: '1047639560548',
    projectId: 'knit-crochet-app-6488e',
    authDomain: 'knit-crochet-app-6488e.firebaseapp.com',
    storageBucket: 'knit-crochet-app-6488e.firebasestorage.app',
    measurementId: 'G-JFFHZXC6TJ',
  );
}
